config/routes.rb
Rails.application.routes.draw do
  get 'todos', to: 'todos#index'
  get 'todos/list', to: 'todos#list', as: 'list'
  get '/todos/new', to: 'todos#new'
  post 'todos', to: 'todos#create'
  get '/todos/:id', to: 'todos#show', as: 'todo'
  get '/todos/:id/edit', to: 'todos#edit', as: 'edit'
  patch 'todos/:id', to: 'todos#update'
  delete 'todos/:id', to: 'todos#destroy', as: 'delete'
  get 'todos/:id/complete', to: 'todos#complete', as: 'complete'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
    validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    def index
        @todos = Todo.all
    end

    def new
        @todo = Todo.new
    end
    

    def create
        @todos = Todo.new(todo_params)
        @todos.save

        if @todos.save == true
            redirect_to todos_path
        else
            alert "Ingrese los campos correctramente"
            redirect_to todos_new_path
        end
    end

    def show
        @todo = Todo.find(params[:id])
    end

    def edit
        @todo = Todo.find(params[:id])
    end

    def update
        @todo = Todo.find(params[:id])
        @todo.update(todo_params)
        redirect_to todos_path
    end

    def destroy
        @todo = Todo.find(params[:id])
        @todo.destroy
        redirect_to todos_path
    end

    def complete
        @todo = Todo.find(params[:id])
        @todo.completed = true
        @todo.save
        redirect_to todos_path
    end

    def list
        @todos = Todo.all
    end
    
    
    

    private
    def todo_params
        params.require(:todo).permit(:description, :completed) 
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

<nav class="navbar navbar-expand-lg navbar-light bg-danger">
<a class="navbar-brand" href="#">Formulario</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarText">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item active">
      <a class="nav-link" <%= link_to 'Index', todos_path %></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" <%= link_to 'List', list_path %></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" <%= link_to 'Form', todos_new_path %></a>
    </li>
  </ul>

</div>
</nav>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h1> Formulario </h1>
<%= form_with  model: @todo, local: true do |f| %>


  <%= f.label :description, "Descripción"%>
  <%= f.text_field :description %>
  </br>
  <%= f.label :completed, "Completed"%>
  <%= f.text_field :completed %>

  </br>
  <%= f.submit "Enviar" %>
<% end %>

app/views/todos/index.html.erb
<h1 class="text-center"> Todos los datos </h1>

<div class="container">
<table class="table">
  <thead>
    <tr>
      <th scope="col">#ID</th>
      <th scope="col">Description</th>
      <th scope="col">Completed</th>
      <th scope="col">Mostrar</th>
      <th scope="col">Edit</th>
      <th scope="col">Eliminar</th>
      <th scope="col">Completado</th>
    </tr>
  </thead>
  <tbody>
    <% @todos.each do |todo| %>
        <tr>
            <td><%=todo.id%></td>
            <td><%=todo.description%></td>
            <td><%=todo.completed%></td>
            <td><%= link_to 'Mostrar', todo_path(todo) %></td>
            <td><%= link_to 'Edit', edit_path(todo) %></td>
            <td><%= link_to 'Delete', delete_path(todo), method: :delete %></td>
             <td><%= link_to 'Completado', complete_path(todo) %></td>
        </tr>
    <% end %>
       

    </tbody>
 </table>
 </table>
  <button type="button" class="btn btn-dark"> <%= link_to 'Crear', todos_new_path%> </button>
 </div>

app/views/todos/list.html.erb
<h1 class="text-center text-dark py-5"> Lista de Formularios </h1>
<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <h1 class="text-center"> Falsos </h1>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Description</th>
            <th scope="col">Completed</th>

          </tr>
        </thead>
        <tbody>
          <% @todos.each do |todo| %>
           <% if todo.completed == false %>
            <tr>
              <td><%=todo.id%></td>
              <td><%=todo.description%></td>
              <td><%=todo.completed%></td>
            </tr>
            
            <% end %>
          <% end %>

        </tbody>
      </table>
    </div>
    <div class="col-sm-6">
      <h1 class="text-center"> Verdaderos </h1>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">ID</th>
            <th scope="col">Description</th>
            <th scope="col">Completed</th>

          </tr>
        </thead>
        <tbody>
          <% @todos.each do |todo| %>
           <% if todo.completed == true %>
            <tr>
              <td><%=todo.id%></td>
              <td><%=todo.description%></td>
              <td><%=todo.completed%></td>
            </tr>
            
            <% end %>
            
          <% end %>

        </tbody>
      </table>

    </div>
  </div>
</div>

app/views/todos/new.html.erb
<div class="container">
<h1> Formulario </h1>
<%= form_with  model: @todo, class:'form', local: true do |f| %>
    <div class="form-group">
  <%= f.label :description, "Descripción"%>
  <%= f.text_field :description %>
  </br>
  <%= f.label :completed, "Completed"%>
  <%= f.text_field :completed %>
  </div>
  <%= f.submit "Enviar" %>
<% end %>
<div class="container">

app/views/todos/show.html.erb
<h1 class="text-center"> Todos los datos </h1>

<div class="container">
<table class="table">
  <thead>
    <tr>
      <th scope="col">#ID</th>
      <th scope="col">Description</th>
      <th scope="col">Completed</th>
    </tr>
  </thead>
  <tbody>
        <tr>
            <td><%=@todo.id%></td>
            <td><%=@todo.description%></td>
            <% if @todo.completed == true%>
                <td><%=@todo.completed = "si"%></td>
            <% else %>
                <td><%=@todo.completed = "no"%></td>
            <% end %>
        </tr>
    </tbody>
 </table>
 </table>
 </div>